config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  mount API => "/"

  root 'home#index'
  get 'home/api_swagger_ui'
  get '/openinapp_instruction' => 'home#openinapp_instruction', as: :openinapp_instruction

  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end


  # 用户相关
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  # 第三方登录
  match "/auth/:provider/callback", :to => 'omniauths#create', via: [:get, :post]
  # 工具相关
  match "/send_verify_code", to: 'tools#send_verify_code', via: :post
  # 微信测试删除好友页面
  match "/wechat_deleted_friends", to: 'tools#wechat_deleted_friends', via: :get
  # 验证微信公众账号
  match "/valid_public_wechat", to: 'tools#valid_public_wechat', via: :get

  resources :users do
    collection do
      get 'verify_email'
    end
    member do
      get :following, :followers, :feeds, :products
    end
  end
  resource :settings do
    collection do
      get :account
    end
  end
  resources :relationships, only: [:create, :destroy]
  # todo 可以把user的功能都放到module下
  scope module: :member do
    resources :collects, only: [:create, :destroy]
    resources :tags, only: [:index]
    # 消息通知
    resources :notifications, only: [:index, :destroy] do
      # collection do
        # get :unread_count
      # end
    end
    # 重置密码
    resources :password_resets
  end

  # 商品相关
  resources :products do
    resources :comments, only: [:create, :destroy]
  end

  # 抓取内容news
  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end

  # 日知文章
  resources :articles do
    resources :article_lists
  end

  # 日知讲座
  resources :chairs


  # 七牛上传文件
  namespace :upload do
    resources :qiniu, only: [] do
      collection do
        get 'image_up_token'
      end
    end
  end

  # 购买功能
  resources :orders


  # 管理员
  draw :admin
  # 新版api
  draw :api

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  user_id    :integer
#  status     :integer          default(0)
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cover_path :string(255)
#  author     :string(255)
#

# 日知栏目
class Article < ActiveRecord::Base
  belongs_to :user
  # 关注
  has_many :user_collects, as: :listable, dependent: :destroy
  # has_many :collected_user, through: :user_collects, source: :listable, source_type: 'Article'
  # 文章期刊
  has_many :article_lists, dependent: :destroy

  # 状态
  enum status: {updating: 0, finished: 1}

  # 验证
  validates_presence_of :user
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 5000 }
end

app/controllers/articles_controller.rb
# encoding=utf-8
class ArticlesController < ApplicationController
	before_action :signed_in_user

	def index
		@articles = Article.paginate(page: params[:page], per_page: 10)
	end

  def new
    @article = current_user.articles.build
  end

  def create
  	article = current_user.articles.build(article_params)
  	if article.save
  		flash[:success] = '栏目创建成功!'
  		redirect_to articles_path
  	else
  		render 'new'
  	end
  end

  def edit
  	@article = current_user.articles.find(params[:id])
  end

  def update
  	article = current_user.articles.find(params[:id])
  	if article.update(article_params)
  		flash[:success] = '栏目编辑成功!'
  		redirect_to articles_path
  	else
  		flash[:success] = '栏目编辑失败!'
  		redirect_to :back
  	end
  end

  private

  	def article_params
  		params.require(:article).permit(:title, :content, :cover_path, :status, :author)
  	end

end

app/views/articles/_form.html.erb
<%= link_to "栏目列表", articles_path, class: "btn btn-primary" %>

<%= simple_form_for @article, validate: true, html: { class: "form-horizontal"} do |f| %>
  <div class="col-sm-8 col-sm-offset-2">
    <%= f.input :author, autofocus: true %>

    <%= f.input :title, input_html: { maxlength: 30 } %>

    <%= f.input :cover_path, input_html: { id: "cover_path", readonly: true } %>
    <a class="btn btn-default btn-lg" id="pickfiles">增加图片</a>
    <br/>
    <img src="<%= @article.cover_path %>" id="show_cover_path" width="100" height="100"/>

    <%= f.input :content, as: :text, input_html: {rows: 20} %>

    <%= f.input :status, as: :radio_buttons, collection: [['更新中', 'updating'], ['已完成', 'finished']] %>

    </br></br></br>
    <%= f.button :submit, "发布栏目", class: 'btn-lg btn-block', data: { disable_with: '发布中...' } %>
  </div>
<% end %>

<!-- qiniu -->
<%= javascript_include_tag 'upload/image_upload' %>
<%= javascript_include_tag 'doc/form_text_check/autogrow' %>

<script>
    $(function () {

      // 封面图
      imageUpload.coverUploader('pickfiles', $('#show_cover_path'), $('#cover_path'));

      // text自动增加列
      $('#article_content').autogrow();

    });
</script>

app/views/articles/edit.html.erb
<% provide(:title, '编辑日知栏目') %>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row">
  <% @articles.each do |article| %>
      <div class="col-sm-6 col-md-3">
        <%= image_tag article.cover_path, size: '80x80' %>
        <div class="thumbnail post-title">
          <div class="caption">
            <h3 class='link_class1'><%= article.title %></h3>
            <p><%= truncate(article.content, length: 30) %></p>
          </div>
          <%= link_to "创建文章期刊",  article_article_lists_path(article), class: "btn btn-info" %>
        </div>
      </div>
  <% end %>
</div>
<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

app/views/articles/new.html.erb
<% provide(:title, '创建日知栏目') %>

<%= render 'form' %>