config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  mount API => "/"

  root 'home#index'
  get 'home/api_swagger_ui'
  get '/openinapp_instruction' => 'home#openinapp_instruction', as: :openinapp_instruction

  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end


  # 用户相关
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  # 第三方登录
  match "/auth/:provider/callback", :to => 'omniauths#create', via: [:get, :post]
  # 工具相关
  match "/send_verify_code", to: 'tools#send_verify_code', via: :post
  # 微信测试删除好友页面
  match "/wechat_deleted_friends", to: 'tools#wechat_deleted_friends', via: :get
  # 验证微信公众账号
  match "/valid_public_wechat", to: 'tools#valid_public_wechat', via: :get

  resources :users do
    collection do
      get 'verify_email'
    end
    member do
      get :following, :followers, :feeds, :products
    end
  end
  resource :settings do
    collection do
      get :account
    end
  end
  resources :relationships, only: [:create, :destroy]
  # todo 可以把user的功能都放到module下
  scope module: :member do
    resources :collects, only: [:create, :destroy]
    resources :tags, only: [:index]
    # 消息通知
    resources :notifications, only: [:index, :destroy] do
      # collection do
        # get :unread_count
      # end
    end
    # 重置密码
    resources :password_resets
  end

  # 商品相关
  resources :products do
    resources :comments, only: [:create, :destroy]
  end

  # 抓取内容news
  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end

  # 日知文章
  resources :articles do
    resources :article_lists
  end

  # 日知讲座
  resources :chairs


  # 七牛上传文件
  namespace :upload do
    resources :qiniu, only: [] do
      collection do
        get 'image_up_token'
      end
    end
  end

  # 购买功能
  resources :orders


  # 管理员
  draw :admin
  # 新版api
  draw :api

end

app/views/shared/_comments.html.erb
<div class="comment-body col-md-12 col-lg-10 col-md-offset-1">
  <div class="comment-list" data-users="<%= comments.map {|c| c.user.name}.uniq %>">
    <% if comments.any? %>
      <%= render comments %>
      <%# comments.each do |comment| %>
        <%#= render 'shared/comment', locals: {comment: comment} %>
      <%# end %>
    <% end %>
  </div>

  <div class="comment-form">
    <%= simple_form_for [product, comment], remote: true do |f| %>
      <%= f.input :content, as: :text, input_html: {rows: 8} %>
      <%= f.button :submit, "保存", id: "comment-submit" %>
    <% end %>
  </div>
</div>

<script>
  $(function(){
    // @功能
    data = $(".comment-list").data("users");
    $('textarea').atwho({at:"@", 'data':data});

    // 提交评论
    // $("#comment-submit").on('click', function(e){
    //   e.preventDefault();
    //   $.ajax({
    //     url: "/products/<%= product.id %>/comments",
    //     type: "post",
    //     data: {comment: {content: "sss"}}
    //   }).done(function(){
    //     $(".comment-list").append($(".comment"));
    //   }).fail(function(){
    //     console.log("fail");
    //   });
    // });
  });
</script>

app/views/shared/_common.mobile.erb
<!doctype html>
<html lang="">
<head>
  <meta charset="utf-8">
  <meta name="description"
        content="react demo, modern mobile web apps.">
  <meta name="viewport"
        content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <!-- Set render engine for 360 browser -->
  <meta name="renderer" content="webkit">

  <!-- No Baidu Siteapp-->
  <meta http-equiv="Cache-Control" content="no-siteapp"/>

  <link rel="icon" type="image/png" href="i/favicon.png">

  <!-- Add to homescreen -->
  <link rel="manifest" href="manifest.json">

  <!-- Fallback to homescreen for Chrome <39 on Android -->
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="application-name" content="Web Starter Kit">
  <link rel="icon" sizes="192x192" href="i/touch/chrome-touch-icon-192x192.png">

  <!-- Add to homescreen for Safari on iOS -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title"
        content="react demo">
  <link rel="apple-touch-icon" href="i/touch/apple-touch-icon.png">

  <!-- Tile icon for Win8 (144x144 + tile color) -->
  <meta name="msapplication-TileImage"
        content="i/touch/ms-touch-icon-144x144-precomposed.png">
  <meta name="msapplication-TileColor" content="#0e90d2">

  <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
  <!--
  <link rel="canonical" href="http://www.example.com/">
  -->

  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'mobile_application', media: 'all' %>
  
  <%= javascript_include_tag 'mobile_application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
  <body>
    
    <div class="root" id="root">
      
  </div>
</body>
</html>

app/views/shared/_function_tips.html.erb
<div class="tips col-sm-0 col-md-2 col-md-offset-1">
	<% case type %>
	<% when "collect" %>
		<div id="collect_<%= product.id %>" class="trip-collect">
			<% if current_user && current_user.collecting?(product, "product") %>
	      <%= render partial: 'member/collects/cancel_collect', locals: {product: product} %>
	    <% else %>
	      <%= render partial: 'member/collects/collect', locals: {product: product} %>
	    <% end %>
	  </div>
		<div class="line"></div>
		<div class="tips_content" id="collect_count"><%= product.user_collect_products_count %> 人收藏了此文章</div>
	
	<% when "info" %>
		<div class="tips_content">文章信息</div>
		<%= user_avatar(product.user.avatar_path, '40x40') %>
		<%= link_to product.user.name, product.user %>
		发布于
		<%= time_ago_in_words product.created_at %>
	
	<% when "category" %>
		<div class="tips_content">所属标签</div>
		<%= product.categories.map(&:name) %>
	
	<% when "watch" %>
		<p><%= link_to "返回文章列表", posts_path, class: "btn btn-info btn-block" %></p>
		<div class="tips_content"><%= watch_count %> 人查看了此文章</div>

	<% when "order" %>
		<div class="tips_content">购买按钮</div>
		<%= link_to "下单", new_order_path, class: "btn btn-primary btn-block" %>

	<% end %>
</div>

app/views/shared/_setting_nav.html.erb
<ol class="breadcrumb">
	<%= nav_link '个人信息', edit_user_path(current_user), 'active' %>
	<%= nav_link '账户信息', account_settings_path, 'active' %>
	<%= nav_link '密码重置', "#", 'active' %>
	<%= nav_link '通知设置', "#", 'active' %>
</ol>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		关注
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="follower" class="stat">
			<%= @user.followers.count %>
		</strong>
		关注者
	</a>
</div>