config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  mount API => "/"

  root 'home#index'
  get 'home/api_swagger_ui'
  get '/openinapp_instruction' => 'home#openinapp_instruction', as: :openinapp_instruction

  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end


  # 用户相关
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  # 第三方登录
  match "/auth/:provider/callback", :to => 'omniauths#create', via: [:get, :post]
  # 工具相关
  match "/send_verify_code", to: 'tools#send_verify_code', via: :post
  # 微信测试删除好友页面
  match "/wechat_deleted_friends", to: 'tools#wechat_deleted_friends', via: :get
  # 验证微信公众账号
  match "/valid_public_wechat", to: 'tools#valid_public_wechat', via: :get

  resources :users do
    collection do
      get 'verify_email'
    end
    member do
      get :following, :followers, :feeds, :products
    end
  end
  resource :settings do
    collection do
      get :account
    end
  end
  resources :relationships, only: [:create, :destroy]
  # todo 可以把user的功能都放到module下
  scope module: :member do
    resources :collects, only: [:create, :destroy]
    resources :tags, only: [:index]
    # 消息通知
    resources :notifications, only: [:index, :destroy] do
      # collection do
        # get :unread_count
      # end
    end
    # 重置密码
    resources :password_resets
  end

  # 商品相关
  resources :products do
    resources :comments, only: [:create, :destroy]
  end

  # 抓取内容news
  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end

  # 日知文章
  resources :articles do
    resources :article_lists
  end

  # 日知讲座
  resources :chairs


  # 七牛上传文件
  namespace :upload do
    resources :qiniu, only: [] do
      collection do
        get 'image_up_token'
      end
    end
  end

  # 购买功能
  resources :orders


  # 管理员
  draw :admin
  # 新版api
  draw :api

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    unless signed_in?
        # render 'cover_home', layout: false
        render 'cover_home_v2', layout: false
    end
  end

  def openinapp_instruction
    # 域名://products?id=1
    render layout: false
  end

end

app/controllers/new_api/v2/home_controller.rb
class NewApi::V2::HomeController < NewApi::V2::BaseController

  def index
    @hot_products = Product.hot.order(id: :desc).last(8)
    @roll_nav_infos = RollNavInfo.order(:weight).last(6)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/cover_home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>创客家族</title>
		<%= favicon_link_tag 'favicon.ico' %>

		<style type="text/css">
		body {
			display: table;
			position: relative;
			width: 100%;
			height: 100%;
			background: url(<%= asset_path "bg#{rand(1..3)}.jpg" %>) no-repeat center center fixed; 
			-webkit-background-size: cover; 
			-moz-background-size: cover; 
			-o-background-size: cover;
			background-size: cover; 
		}
		.cover-login {
			background-color: white;
			width: 40%;
			margin-left: auto;
			margin-right: auto;
			text-align: center;
			line-height: 50px;
			border: 5px solid #dedede;
			-moz-border-radius: 15px;      /* Gecko browsers */
			-webkit-border-radius: 15px;   /* Webkit browsers */
			border-radius:15px;            /* W3C syntax */
		}
		ul {
			list-style: none;
		}
		ul li {
			font-size: 25px;
			font-weight: bold;
			/*font-style: italic;*/
		}
		ul li a {
			text-decoration: none;
			color: black;
		}
		ul li a:hover {
			text-decoration: underline;
		}
		</style>
	</head>

		<body>
			<div class="cover-login">
				<ul class="login-way">
					<li><%= link_to "登录", login_path %></li>
					<li><%= link_to "注册", new_user_path %></li>
					<li><%= link_to "weixin登录", "/auth/open_wechat" %></li>
					<li><%= link_to "微博登录", "/auth/weibo" %></li>
					<li><%= link_to "qq登录", "/auth/qq_connect" %></li>
					<li><%= link_to "豆瓣登录", "/auth/douban" %></li>
					<li><%= link_to "github登录", "/auth/github" %></li>
					<li><%= link_to "随便看看", posts_path %></li>
    				</ul>
			</div>
		</body>
</html>

app/views/home/cover_home_v2.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>创客家族 - 首页</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag "single/cover_home_v2" %>
    <%= stylesheet_link_tag "doc/top_pmgressbar/pace-theme-flash" %>
    <%= javascript_include_tag 'doc/top_pmgressbar/pace.min' %>
</head>

<body class="signin">
    <div class="signinpanel">
        <div class="row">
            <div class="col-sm-7">
                <div class="signin-info">
                    <div class="logopanel m-b">
                        <h1>[ 创客家族 ]</span></h1>
                    </div>
                    <div class="m-b"></div>
                    <h4>让商业 <strong>更加简单</strong></h4>
                    <ul class="m-b">
                        <li><i class="fa fa-arrow-circle-o-right m-r-xs"></i> 优势一</li>
                        <li><i class="fa fa-arrow-circle-o-right m-r-xs"></i> 优势二</li>
                        <li><i class="fa fa-arrow-circle-o-right m-r-xs"></i> 优势三</li>
                        <li><i class="fa fa-arrow-circle-o-right m-r-xs"></i> 优势四</li>
                        <li><i class="fa fa-arrow-circle-o-right m-r-xs"></i> 优势五</li>
                    </ul>
                    <strong>还没有账号？ <a href="<%= new_user_path %>">立即注册&raquo;</a></strong>
                </div>
            </div>
            <div class="col-sm-5">
                <%= simple_form_for :session, url: sessions_path do |f| %>
                    <h4 class="no-margins">登录：</h4>
                    <p class="m-t-md">还不快登录?</p>
                    <%= f.input :name, input_html: { maxlength: 50, class: 'form-control uname', placeholder: "用户名" }, label: false, autofocus: true %>
                    <%= f.input :password, input_html: { maxlength: 30, class: 'form-control pword m-b', placeholder: "密码" }, label: false %>
                    <a href="/password_resets/new">忘记密码了？</a>
                    <%= f.button :submit, "登录", class: 'btn btn-success btn-block', data: { disable_with: '登录中...' } %>
                <% end %>
            </div>
        </div>
        <div class="signup-footer">
            <div class="pull-left">
                &copy; 2015 All Rights Reserved. xxx
            </div>
        </div>
    </div>
</body>

</html>

app/views/home/cover_home_v2.mobile.erb
<%= render 'shared/common' %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>一起去探索属于创客的领域!</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Go</a></p>
</div>
<h1><%= t(:hello) %></h1>

<%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-CN" %>
<%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>

app/views/home/openinapp_instruction.mobile.erb
<!doctype html>
<html lang="">
<head>
  <meta charset="utf-8">
  <meta name="description"
        content="react demo, modern mobile web apps.">
  <meta name="viewport"
        content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <link rel="icon" type="image/png" href="i/favicon.png">
  <link rel="manifest" href="manifest.json">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="application-name" content="Web Starter Kit">
  <link rel="icon" sizes="192x192" href="i/touch/chrome-touch-icon-192x192.png">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title"
        content="react demo">
  <link rel="apple-touch-icon" href="i/touch/apple-touch-icon.png">
  <meta name="msapplication-TileImage"
        content="i/touch/ms-touch-icon-144x144-precomposed.png">
  <meta name="msapplication-TileColor" content="#0e90d2">
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <style type="text/css">
    .openinapp-instruction-page {
      width: 100%;
      height: 100%;
      margin: 0;
      padding: 0;
      background-color: #efeff4;
      text-align: center;
      position: fixed;
      top: 0;
      left: 0;
    }
    .inner {
      width: 235px;
      margin: 0 auto;
      margin-bottom: 37px;
      margin-top: -122px;
      position: relative;
      top: 50%;
    }
    .instruction-title {
      font-size: 18px;
      font-weight: 600;
      color: #333;
      margin-bottom: 35px;
    }
    .instr-left {
      float: left;
    }
    .instr-right {
      float: right;
    }
    .icon-middle {
      margin-top: 25px;
      margin-left: 10px;
    }
    .clearfix:after {
      content: "";
      display: table;
      clear: both;
    }
    .icon-instruction {
      margin-bottom: 20px;
    }
    .step-content {
      font-size: 12px;
      color: #666;
    }
    .step {
      font-size: 16px;
      font-weight: 700;
      color: #666;
      margin-bottom: 10px;
    }
  </style>

</head>
  <body>
    <div class="openinapp-instruction-page">
      <div class="inner">

        <p class="instruction-title">
         请按照下面的示意图操作打开
         <br/>
         xxx App
        </p>

        <div class="instructions clearfix">
          <div class="instr-left">
            <img src="http://www.zhihu.com/static/img/openinapp_instruction/android_more.png" class="icon-instruction" width="72" height="72">
            <p class="step">
              第 1 步
            </p>
            <p class="step-content">
              点击该页右上角<br>的「更多」按钮
            </p>
          </div>

          <img src="http://www.zhihu.com/static/img/openinapp_instruction/android_arrow.png" class="icon-middle" width="11" height="18">

          <div class="instr-right">
            <img src="http://www.zhihu.com/static/img/openinapp_instruction/android_web.png" class="icon-instruction" width="72" height="72">
            <p class="step">
              第 2 步
            </p>
            <p class="step-content">
              选择在浏览器中打开
            </p>
          </div>
        </div>

      </div>
    </div>  
    
  </body>
</html>